name: Add fragrances
on:
  schedule:
    - cron: "0 18 * * *"
jobs:
  fragrances:
    name: Search and add new fragrances
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install requests
      - name: Add fragrances
        run: python add_fragrances.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Add fragrances
          title: Add fragrances
          body: Add fragrances
          base: main
          labels: automated-pr, fragrances
          branch: add-fragrances
          delete-branch: true
